version: "2.1"

services:

  stgrest:
    image: subzerocloud/postgrest
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_URI=postgres://postgres:postgres@postgres:5432/postgres
      - DB_SCHEMA=api
      - DB_ANON_ROLE=web_anon
      - JWT_SECRET=postgres
    mem_limit: 30m
    memswap_limit: 30m
    networks:
      - stgrest-tut-network
    restart: always

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_scripts/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    networks:
      - stgrest-tut-network

networks:
  stgrest-tut-network:
    driver: bridge
